README.md
=> 创建分支develop-13

wuyu-server/pom.xml, wuyu-server/src/main/java/com/fiveup/core/FiveupCoreApplication.java, wuyu-server/src/main/java/com/fiveup/core/login/service/UserService.java
=> fix: 解决跨域问题

wuyu-front/src/api/schedulModule/index.js, wuyu-front/src/router/index.js, wuyu-front/src/utils/request.js, wuyu-front/src/views/scheduling-management/index.vue
=> Feature 02 yaling

wuyu-server/src/main/java/com/fiveup/core/noticeBooklet/domain/NoticeBooklet.java, wuyu-server/src/main/java/com/fiveup/core/noticeBooklet/mapper/ScoreMapper.java, wuyu-server/src/main/java/com/fiveup/core/noticeBooklet/service/impl/NoticeBookletServiceImpl.java, wuyu-server/src/main/resources/mapper/noticeBooklet/ScoreMapper.xml, wuyu-server/src/test/java/com/fiveup/core/PanelTest.java
=> fix: 修复学生、五育成绩数据来源问题

wuyu-server/src/main/java/com/fiveup/core/teacherworkspace/controller/LessonController.java, wuyu-server/src/main/java/com/fiveup/core/teacherworkspace/mapper/LessonMapper.java, wuyu-server/src/main/java/com/fiveup/core/teacherworkspace/model/dto/PageLessonDto.java, wuyu-server/src/main/java/com/fiveup/core/teacherworkspace/service/LessonService.java, wuyu-server/src/main/java/com/fiveup/core/teacherworkspace/service/impl/LessonServiceImpl.java
feat: 新增学年学期的相关条件查询，新增学年列表的接口开发，优化参数校验的设计
=> feat: 新增学年学期的相关条件查询，新增学年列表的接口开发，优化参数校验的设计

wuyu-server/src/main/java/com/fiveup/core/teacherworkspace/common/utils/AlgorithmUtils.java, wuyu-server/src/main/java/com/fiveup/core/teacherworkspace/controller/LessonController.java, wuyu-server/src/main/java/com/fiveup/core/teacherworkspace/scheduled/AutoCopyLessonScheduled.java, wuyu-server/src/main/java/com/fiveup/core/teacherworkspace/service/impl/LessonExcelServiceImpl.java, wuyu-server/src/main/java/com/fiveup/core/teacherworkspace/service/impl/LessonServiceImpl.java
refactor: 优化分页课程顺序，优化复制课程接口参数设计
=> refactor: 优化分页课程顺序，优化复制课程接口参数设计

wuyu-front/src/api/managementModule/student.js, wuyu-front/src/layout/components/Sidebar/index.vue, wuyu-front/src/main.js, wuyu-front/src/router/index.js, wuyu-front/src/store/modules/permission.js, wuyu-front/src/utils/ruoyi.js, wuyu-front/src/views/commentgeneration/class.vue
=> feat-通知册页面展示

wuyu-server/pom.xml, wuyu-server/src/main/java/com/fiveup/core/noticeBooklet/controller/NoticeBookletWordController.java, wuyu-server/src/main/java/com/fiveup/core/noticeBooklet/service/NoticeBookletWordService.java, wuyu-server/src/main/java/com/fiveup/core/noticeBooklet/service/impl/NoticeBookletWordServiceImpl.java, wuyu-server/src/main/java/com/fiveup/core/noticeBooklet/utils/SingleWordUtils.java, wuyu-server/src/main/resources/templates/notice_booklet.html
=> 根据通知册内容生成word

wuyu-server/pom.xml, wuyu-server/src/main/resources/application.yml
=> fix: 修改后端端口，添加缺少依赖

wuyu-front/src/api/notice.js
=> 新增工作台页面与通告获取api

wuyu-front/src/api/notice.js, wuyu-front/src/views/workbench/index.vue
修改api中的多余行(import), 编辑工作台的公告显示与js
=> 修改api中的多余行, 编辑工作台的公告显示与js

wuyu-front/src/router/index.js, wuyu-front/src/views/school-overview/index.vue, wuyu-front/vue.config.js, wuyu-server/src/main/java/com/fiveup/core/notice/controller/noticeController.java, wuyu-server/src/main/java/com/fiveup/core/notice/service/impl/noticeServiceImpl.java, wuyu-server/src/main/java/com/fiveup/core/notice/service/noticeService.java
=> 修改:通知公告可以正常获取显示

wuyu-server/src/main/java/com/fiveup/core/notice/dto/NoticePageQuery.java, wuyu-server/src/main/java/com/fiveup/core/notice/mapper/noticeMapperExtendBaseMapper.java, wuyu-server/src/main/java/com/fiveup/core/notice/vo/NoticeVO.java, wuyu-server/src/main/java/com/fiveup/core/notice/vo/PageResult.java
=> 修改增加通知公告所需类,使功能正常运行

wuyu-server/src/main/java/com/fiveup/core/notice/mapper/noticeMapper.java, wuyu-server/src/main/java/com/fiveup/core/notice/service/impl/noticeServiceImpl.java, wuyu-server/src/main/resources/mapper/notice/noticeMapper.xml
=> Feature 01 tsp 通知状态后端代码完善

wuyu-front/src/views/school-overview/index.vue, wuyu-server/src/main/java/com/fiveup/core/notice/service/impl/noticeServiceImpl.java
=> 修改前端获取通告集合代码显示

wuyu-front/src/api/courseScore.js, wuyu-front/src/router/index.js, wuyu-front/src/utils/request.js, wuyu-front/src/views/course_score/charts.vue, wuyu-server/fiveup-core.iml, wuyu-server/src/main/java/com/fiveup/core/courseScore/controller/CourseScoreController.java, wuyu-server/src/main/java/com/fiveup/core/courseScore/mapper/CourseScoreMapper.java, wuyu-server/src/main/java/com/fiveup/core/courseScore/service/CourseScoreService.java, wuyu-server/src/main/java/com/fiveup/core/courseScore/service/impl/CourseScoreServiceImpl.java
本次 PR 完成**成绩可视化分析模块**开发，包含 3 项核心功能：  
1. **成绩分布柱状图**：支持按**课程名称+考试序号**查询，展示分数段占比，前后端联调完成。  
2. **个人成绩趋势图**：支持查询**单个学生**多场考试成绩变化，可对比多科目分数趋势。  
3. **多科综合雷达图**：支持**单个学生**的多科成绩的雷达图展示，分析学科能力分布。
=> feat: 成绩可视化模块迭代（柱状图+趋势图+雷达图全量上线）

wuyu-server/src/main/java/com/fiveup/core/fuScale/controller/FuScaleController.java, wuyu-server/src/main/java/com/fiveup/core/fuScale/mapper/FuScaleMapper.java, wuyu-server/src/main/java/com/fiveup/core/fuScale/model/ScaleInfo.java, wuyu-server/src/main/java/com/fiveup/core/fuScale/service/FuScaleService.java, wuyu-server/src/main/resources/mapper/fuScale/FuScaleMapper.xml
=> 后端-评价量表bug修复

wuyu-server/src/main/java/com/fiveup/core/noticeBooklet/controller/AIController.java, wuyu-server/src/main/java/com/fiveup/core/noticeBooklet/utils/AIUtil.java, wuyu-server/src/test/java/com/fiveup/core/PanelTest.java
=> Feature 06 hyh

wuyu-front/src/views/user_management/user_manage.vue
前端-新增了用户状态管理功能，可通过开关切换用户状态，且对校长角色进行保护，禁止禁用。
=> 前端-用户禁用与启用状态切换

wuyu-front/src/views/teacher/teacher.vue, wuyu-server/src/main/java/com/fiveup/core/teacher/Service/teacherFiveupService.java, wuyu-server/src/main/java/com/fiveup/core/teacher/controller/teacherFiveupController.java
=> Feature 05 ljh

wuyu-server/src/main/java/com/fiveup/core/studentManager/mapper/StudentManagerMapper.java, wuyu-server/src/main/java/com/fiveup/core/studentManager/service/impl/StudentManagerServiceImpl.java
=> Revert "增加了在学生添加的时候判断学号是否重复的功能"

.idea/jarRepositories.xml, package-lock.json, wuyu-front/src/api/classGradeScore.js, wuyu-front/src/router/index.js, wuyu-front/src/utils/request.js, wuyu-front/src/views/teacher_workspace/diagnose/ClassGradeRadar.vue, wuyu-front/vue.config.js, wuyu-server/src/main/java/com/fiveup/core/diagnose/controller/studentscoreController.java, wuyu-server/src/main/java/com/fiveup/core/diagnose/mapper/studentscoreMapper.java, wuyu-server/src/main/java/com/fiveup/core/diagnose/service/studentscoreService.java
=> Feature 04 zyj
